name: Deploy ABC Startup Infrastructure

on:
  push:
    branches:
      - main

permissions:
  id-token: write        # Required for OIDC
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Authenticate to AWS using OIDC
      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::165742852730:role/GitHubActions-IaC-Deployer
          aws-region: ap-south-1

      # Install Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # Deploy infrastructure
      - name: Terraform Init & Apply
        run: |
          terraform init
          terraform apply -auto-approve
