name: Terraform Import

on:
  workflow_dispatch

permissions:
  id-token: write
  contents: read

jobs:
  import:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::165742852730:role/GitHubActions-IaC-Deployer
          aws-region: ap-south-1
      - uses: hashicorp/setup-terraform@v3

      - run: terraform init
      - run: terraform import aws_iam_instance_profile.ec2_profile abc-startup-ec2-profile
      - run: terraform import aws_s3_bucket.transactions 2472737-usecase-bucket
